---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: copy a file
      copy:
        src: /tmp/abcd2
        dest: /tmp
        owner: nikhil
        group: root
        mode: 0777
      when: ansible_distribution == "Ubuntu"
