---
- name: Install nginx and start service
  hosts: all
  remote_user: root
  become: yes
  tasks:
  - name: install nginx
    apt:
      name: nginx
      state: latest

  - name: install nginx
    service:
      name: nginx
      state: started
