---
- name: Add Issue to Jira Project
  hosts: ec2-54-198-250-47.compute-1.amazonaws.com
  gather_facts: yes
  tasks:
    - name: Add Jira Issue
      uri:
        url: "http://54.198.250.47:8080/rest/api/2/issue/"
        method: POST
        user: "ridam.kundu"
        password: "ridamK@123"
        force_basic_auth: yes
        status_code: 201  # Expected status code for successful creation
        body_format: json
        body: |
          {
            "fields": {
                "project": {
                    "key": "CLOUD"
                },
                "summary": "Example Issue",
                "description": "This is an example issue created by Ansible",
                "issuetype": {
                    "name": "Task"
                }
            }
          }

      register: jira_response

    - name: Display Jira Response
      debug:
        var: jira_response.json
