---
- name: Create Jira Project
  hosts: 54.165.145.22:8080
  gather_facts: yes
  tasks:
    - name: Create Jira Project
      uri:
        url: "http://54.198.250.47:8080/rest/api/2/project/"
        method: POST
        user: "ridam.kundu"
        password: "ridamK@123"
        force_basic_auth: yes
        status_code: 201  # Expected status code for successful creation
        body_format: json
        body: |
          {
            "key": "DEV",
            "name": "GCP",
            "projectTypeKey": "software",
            "projectTemplateKey": "com.pyxis.greenhopper.jira:gh-kanban-template",
            "description": "This is a new project created by Ansible",
            "lead": "ridam.kundu",
            "assigneeType": "PROJECT_LEAD"
          }
      register: jira_response

    - name: Display Jira Response
      debug:
        var: jira_response.json
