---
- name: Add Issue to Jira Project
  hosts: ec2-54-198-250-47.compute-1.amazonaws.com
  gather_facts: yes
  tasks:
    - name: Create Jira Issue
      uri:
        url: "http://54.198.250.47:8080/rest/api/2/issue/"
        method: POST
        user: "ridam.kundu"
        password: "ridamK@123"
        force_basic_auth: yes
        status_code: 201  # Expected status code for successful creation
        body_format: json
        body: |
          {
            "fields": {
              "project": {
                "key": "GCP"  # Replace with your Jira project key
              },
              "summary": "New Issue Summary",
              "description": "This is a new issue created by Ansible",
              "issuetype": {
                "name": "Task"  # Replace with the appropriate issue type
              },
              "assignee": {
                "name": "ridam.kundu"  # Assign the issue to a user
              }
            }
          }
      register: jira_issue_response

    - name: Display Jira Issue Response
      debug:
        var: jira_issue_response.json
